### ISSUE TITLE
Synchronisation error?

### ISSUE THREAD

**Issue by 4676rich** [aluxnimm/outlookcaldavsynchronizer#109]
Hi CalDAV.  Love this app, but I'm getting the following report on every synch - even though the synch seems to work just fine.  I'm not technical enough to know what it means or how to resolve it - can you help?  

![caldav report](https://cloud.githubusercontent.com/assets/17011990/12728422/e8961400-c975-11e5-86ab-b57493982de4.png)
![caldav settings1](https://cloud.githubusercontent.com/assets/17011990/12728428/ec9d2c3c-c975-11e5-89cd-f81372549f2f.png)

Thanks, 4676rich

_<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>rich.britton13@gmail.com</ProfileName>
  <ProfileId>831ea901-267d-4567-b140-384f9abe8a79</ProfileId>
  <StartTime>2016-02-01T02:23:03.0032847Z</StartTime>
  <InitialEntityMatchingPerformed>false</InitialEntityMatchingPerformed>
  <ADelta>Unchanged: 55 , Added: 1 , Deleted 0 ,  Changed 0</ADelta>
  <BDelta>Unchanged: 54 , Added: 1 , Deleted 0 ,  Changed 1</BDelta>
  <LoadErrors />
  <EntitySynchronizationReports>
    <EntitySynchronizationReport>
      <MappingErrors />
      <AId>00000000BD6E59E7DA82F34EB9875C2C6F116C6F07001B12FC392EC1374A9FF936D53D99C08B00000000020200001B12FC392EC1374A9FF936D53D99C08B0000000008520000</AId>
      <BId />
      <ExceptionThatLeadToAbortion>System.Runtime.InteropServices.COMException (0x8C540201): The item could not be found.
   at Microsoft.Office.Interop.Outlook.AddressEntry.get_AddressEntryUserType()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.GetMailUrlOrNull(AddressEntry addressEntry, String address)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapAttendees1To2(AppointmentItem source, IEvent target, Boolean&amp; organizerSet)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItem source, IEvent target, Boolean isRecurrenceException, iCalTimeZone startIcalTimeZone, iCalTimeZone endIcalTimeZone)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItemWrapper sourceWrapper, IICalendar existingTargetCalender, IEntityMappingLogger logger)
   at GenSync.Synchronization.States.CreateInB`6.&lt;&gt;c__DisplayClass2.&lt;PerformSyncActionNoThrow&gt;b__0(TBtypeEntity b)
   at CalDavSynchronizer.Implementation.CalDavRepository.&lt;Create&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.CreateInB`6.&lt;PerformSyncActionNoThrow&gt;d__4.MoveNext()</ExceptionThatLeadToAbortion>
    </EntitySynchronizationReport>
  </EntitySynchronizationReports>
  <Duration>00:00:03.5628655</Duration>
</SynchronizationReport>_

**Comment by aluxnimm** [comment]
Some strange Outlook Exception when trying to access the adressentry of an attendee of a meeting. Do you use an exchange account with GAL or some special adressbook?

**Comment by aluxnimm** [comment]
Catching exception in commit https://github.com/aluxnimm/outlookcaldavsynchronizer/commit/13209221565d212ec25959986b604cc86bff015a
Recipient will be ignored in that case.

**Comment by 4676rich** [comment]
Thanks Alex – not sure what you did here but it seems to have gone away.  Great response speed, too.  Richard
