### ISSUE TITLE
SabreDav SameOrganizerForAllComponentsException

### ISSUE THREAD

**Issue by schtritoff** [aluxnimm/outlookcaldavsynchronizer#111]
I have this error:
```xml
<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>someprofile</ProfileName>
  <ProfileId>2f7cecaf-e114-46b6-a678-481fa2115211</ProfileId>
  <StartTime>2016-02-08T20:59:48.0763773Z</StartTime>
  <InitialEntityMatchingPerformed>false</InitialEntityMatchingPerformed>
  <ADelta>Unchanged: 53 , Added: 0 , Deleted 0 ,  Changed 1</ADelta>
  <BDelta>Unchanged: 54 , Added: 0 , Deleted 0 ,  Changed 0</BDelta>
  <LoadErrors />
  <EntitySynchronizationReports>
    <EntitySynchronizationReport>
      <MappingErrors />
      <AId>000000002A1B480967583E4E9E876728FD5B3C7FE46AC100</AId>
      <BId>CalDavSynchronizer.DataAccess.WebResourceName</BId>
      <ExceptionThatLeadToAbortion>System.Net.Http.HttpRequestException: Response status code does not indicate success: '500' ('InternalServerError'). Message:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"&gt;
  &lt;s:sabredav-version&gt;3.1.1&lt;/s:sabredav-version&gt;
  &lt;s:exception&gt;Sabre\VObject\ITip\SameOrganizerForAllComponentsException&lt;/s:exception&gt;
  &lt;s:message&gt;Every instance of the event must have the same organizer.&lt;/s:message&gt;
&lt;/d:error&gt;

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;EnsureSuccessStatusCode&gt;d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequest&gt;d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReturnResponseHeaders&gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.&lt;UpdateEntity&gt;d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.UpdateAToB`6.&lt;PerformSyncActionNoThrow&gt;d__4.MoveNext()</ExceptionThatLeadToAbortion>
    </EntitySynchronizationReport>
  </EntitySynchronizationReports>
  <Duration>00:00:04.0634063</Duration>
</SynchronizationReport>
```

I could be something with Sabre Vobject exeption (https://github.com/fruux/sabre-vobject/blob/master/lib/ITip/SameOrganizerForAllComponentsException.php) but I don't know. How to detect which particular calendar entry lead to this exception? Http 500 code indicate that the problem is on the server side and not MS Outlook / outlookcaldavsynchronizer.

My server side ics files are named like this:
![untitled](https://cloud.githubusercontent.com/assets/419794/12899159/7202555c-ceb0-11e5-8314-9d5d1e5112a1.png)

**Comment by aluxnimm** [comment]
You changed one meeting in Outlook (or got an meeting update). It must have been an recurring meeting with one exception with a different organizer. I am not sure how that can be created in Outlook 

A fix could be sync with mode Outlook <- Server (Replicate) once so that the server overwrites that meeting again.

**Comment by schtritoff** [comment]
Thanks, that fixed it
