### ISSUE TITLE
HTTP Status 404 when syncing with Google Calendar

### ISSUE THREAD

**Issue by wrstlbrnft** [aluxnimm/outlookcaldavsynchronizer#114]
I'm using v.1.18.0.0 on Outlook 2016. When syncing (two-way) with my Google calendar, I get a "404 not found" error:

```
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '404' ('NotFound'). Message:
<?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>notFound</code>
  <internalReason>Not Found</internalReason>
 </error>
</errors>

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.WebDavDataAccess.<IsResourceType>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.Synchronizer`6.<SynchronizeNoThrow>d__14.MoveNext()
```

There are no associated load errors or entity sync reports.
What went wrong? Can I find an offending item and fix it?

**Comment by aluxnimm** [comment]
Did you autodiscover the right url with test settings?

**Comment by wrstlbrnft** [comment]
Hi, thanks for the quick reply! I had previously used autodiscover and synced the calendar several times successfully. Now I did another autodiscover and it works again. Is it possible that the server-side URL changes? Or what could have been the issue?

**Comment by aluxnimm** [comment]
If you changed the calendar name in google maybe?
