### ISSUE TITLE
Error Root Element missing (Sync Outlook 2013 -> Google Calender

### ISSUE THREAD

**Issue by bernhardberg** [aluxnimm/outlookcaldavsynchronizer#123]
During Sync between Outlook 2013 and Goolge Calander there comes following error:

System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read4_Item()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at GenSync.EntityRelationManagement.EntityRelationDataAccess`5.LoadEntityRelationData()
   at GenSync.Synchronization.Synchronizer`6.<SynchronizeNoThrow>d__14.MoveNext()

**Comment by aluxnimm** [comment]
just try clear cache in the sync profile and sync again.

**Comment by bernhardberg** [comment]
Thx for the hint but still the same issue

<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>TMA</ProfileName>
  <ProfileId>ab3098fe-50c5-4e0b-8331-8501040db35a</ProfileId>
  <StartTime>2016-03-29T06:14:27.0508Z</StartTime>
  <LoadErrors />
  <EntitySynchronizationReports />
  <ExceptionThatLeadToAbortion>System.InvalidOperationException: There is
an error in XML document (0, 0). ---&gt; System.Xml.XmlException: Root
element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at
Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read4_Item()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader
xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at
GenSync.EntityRelationManagement.EntityRelationDataAccess`5.LoadEntityRelationData()
   at
GenSync.Synchronization.Synchronizer`6.&lt;SynchronizeNoThrow&gt;d__14.MoveNext()</ExceptionThatLeadToAbortion>
  <Duration>00:00:00.3510000</Duration>
</SynchronizationReport>



Alex Nimmervoll <notifications@github.com> schrieb am Di., 29. März 2016 um
10:53 Uhr:

> just try clear cache in the sync profile and sync again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/123#issuecomment-202783749>
>
-- 

_______________________________

 *Bernhard Berg*

 Pachergasse 18/2/7, 2344 Maria Enzersdorf, Austria
Mobil:       +43 664 88 478 185
Mobil:       +43 680 307 0021

Bernhard.Berg@gmail.com <Bernhard.berg@ventum.com>

http://weltreise.bergweb.cc

*Quo** ego sum profectus est*

**Comment by aluxnimm** [comment]
This error can't happen with a new sync run without a cache. Maybe the clear cache didn't work. 
There is a subfolder in  C:\Users\<Your Username>\AppData\Local\CalDavSychronizer for your sync profile, just delete the xml file in this subfolder manually. Or if If you activated Store data in roaming folder the location is changed to the following folder:

    C:\Users\<Your Username>\AppData\Roaming\CalDavSychronizer
