### ISSUE TITLE
Where did I go wrong?

### ISSUE THREAD

**Issue by SkunkWerks7** [aluxnimm/outlookcaldavsynchronizer#129]
I've tried various routes to entering the DAV Url, various means of authenticating.  every time it's the same result.  No response from server...

...

Alright, after "simplifying" the Url a bit, I've managed to get it down to a SSL/TLS issue.  Says it's an invalid cert- but I already know the issue there.

![screenshot 1061](https://cloud.githubusercontent.com/assets/18739816/14923657/67a4f84e-0e0c-11e6-9d20-93af648df763.jpg)

Possibly also meaningful:

_CalDavSynchronizer.DataAccess.WebDavClientException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [IP REDACTED]
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetAllVersions>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Contacts.CardDavRepository.<GetAllVersions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.<SynchronizeNoThrow>d__17.MoveNext()_

How do I get this to accept a self-signed cert?

**Comment by nertsch** [comment]
"How do I get this to accept a self-signed cert?"
Please read the readme.md: 
"If you have problems with SSL/TLS and self-signed certificates, you can change the following settings at your own risk. The recommended way would be to add the self signed cert to the Local Computer Trusted Root Certification Authorities You can import the cert by running the MMC as Administrator.

    - Disable Certificate Validation set to true to disable SSL/TLS certificate validation, major security risk, use with caution!
    - Enable Tls12 set to false to disable TLS12, not recommended
    - Enable Ssl3 set to true to enable deprecated SSLv3, major security risk, use with caution!
"

br
Gerhard

**Comment by SkunkWerks7** [comment]
Yep.  Read that.  But here's the thing- I've already trusted self-signed certs from this server for mail (incoming and outgoing).  If there's a different one in play for this purpose, I'm not being given an opportunity to download it much less add it to trusted.  

It just keels and errors-out unhelpfully.

**Comment by aluxnimm** [comment]
when you trust a cert in a browser or outlook it doesn't automatically mean it is trusted from the .Net framework. Therefore tge self signed cert must be downloaded manually in a browser and imported in the local computer store.

**Comment by SkunkWerks7** [comment]
I'm new at this Cert thing- the vagaries, the totally-necessary neurosis...  you'll have to pardon me while I ululate a well-deserved _*groan*_

Having got that out of my system, I don't have a way to manually download this that I am aware of.

Any ideas?

**Comment by aluxnimm** [comment]
so why don't you just use tfe general option Disable Certificate Validation if you gave trouble with the certificate handling.

**Comment by SkunkWerks7** [comment]
Partly because there are dire warnings sat around that option suggesting that nothing short of forty days and forty nights of flooding will occur should I check the box, partly because that would make me a bad person who should feel bad, and partly because I'd prefer to take advantage of what protections I can.

**Comment by aluxnimm** [comment]
then check msdn for help  e.g.
https://msdn.microsoft.com/en-us/library/ms788967.aspx

closing since no bug but a windows support question.

**Comment by SkunkWerks7** [comment]
Well, considering most products that deal with certs seem to better automate the process of bringing in even a self-signed cert I'd have thought this was a question more relevant to your software, but hey, why not, pass the buck.

Cheerio

**Comment by evert** [comment]
I'd definitely say that there's nothing wrong with using self-signed certificates, but disabling verification _absolutely_ is the wrong advice, in almost every situation.

**Comment by aluxnimm** [comment]
wasn't our first advice. we mentioned the risks and provided links and info how to import the cert first.
