### ISSUE TITLE
Outlook 2013 <--> Google calendar issue

### ISSUE THREAD

**Issue by ctcaveman** [aluxnimm/outlookcaldavsynchronizer#144]
Hi!

Im trying to sync Outlook 2013 with Google calendar but having problems that I don't understand. As far as I've understood it tells me the sync was unsuccessful partly. Would appriciate if I could get some help into interpreting this.

**Indication that something synced**
![github screenshot - caldav sync error](https://cloud.githubusercontent.com/assets/20343589/16837184/0b1c0666-49c2-11e6-93b6-d6fd6dffca57.png)

**Error message**
 Since this is a public forum I've just replaced my google login username with "username" in the snippet below. 

> <?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ProfileName>Cave - Google calendar</ProfileName>
  <ProfileId>ed82d023-af8a-460f-b6a1-81798945f2cc</ProfileId>
  <StartTime>2016-07-14T10:31:46.6833223Z</StartTime>
  <ADelta>Unchanged: 119 , Added: 24 , Deleted 0 ,  Changed 0</ADelta>
  <BDelta>Unchanged: 119 , Added: 355 , Deleted 0 ,  Changed 0</BDelta>
  <LoadErrors />
  <EntitySynchronizationReports>
    <EntitySynchronizationReport>
      <MappingErrors />
      <MappingWarnings />
      <BId>/caldav/v2/username%40gmail.com/events/4r3qogf5aucd2af4o9v57s5rnk%40google.com.ics</BId>
      <ExceptionThatLeadToAbortion>System.ArgumentException: Sorry, something went wrong. You may want to try again.
   at Microsoft.Office.Interop.Outlook._AppointmentItem.Respond(OlMeetingResponse Response, Object fNoUI, Object fAdditionalTextDialog)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IEvent source, IReadOnlyCollection`1 recurrenceExceptionsOrNull, AppointmentItemWrapper targetWrapper, Boolean isRecurrenceException, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, AppointmentItemWrapper target, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.Create(Func`2 entityInitializer)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.&lt;PerformOperations&gt;d__2.MoveNext()</ExceptionThatLeadToAbortion>
    </EntitySynchronizationReport>

> 

Thanks  from 

C

**Comment by aluxnimm** [comment]
Some undefined outlook error when trying to accept a meeting invite. Try with event mapping configuration map attendees and organizer unchecked maybe?

**Comment by ctcaveman** [comment]
Thanks!

This seemed to solve the problem! ☺
