### ISSUE TITLE
After update to 2.5.0 "A task was canceled" occured very often

### ISSUE THREAD

**Issue by big-chen** [aluxnimm/outlookcaldavsynchronizer#163]
Just after updating to release 2.5.0. I receive plenty of these exceptions:
```
INFO  2016-09-03 11:58:58,533 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'Familie''
 INFO  2016-09-03 11:58:58,534 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - Entered. Syncstrategy 'OneWayInitialSyncStateCreationStrategy_BToA`6' with Atype='ContactItemWrapper' and Btype='vCard'
 INFO  2016-09-03 11:58:58,711 [ VSTA_Main] mplementation.Contacts.CardDavRepository . MoveNext                       - Starting 'CardDavRepository.GetVersions'
 INFO  2016-09-03 12:03:58,712 [ VSTA_Main] mplementation.Contacts.CardDavRepository . MoveNext                       - Duration of 'CardDavRepository.GetVersions': 00:04:59.9904219
 ERROR 2016-09-03 12:03:58,713 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - 
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetAllVersions>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Contacts.CardDavRepository.<GetAllVersions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.<SynchronizeNoThrow>d__17.MoveNext()
 INFO  2016-09-03 12:03:58,714 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'Familie'': 00:05:00.1697020
```

This happens for all Repositories, that I've configured, all running on one ownCloud Server. 
Increasing the general timeout to 300 helped a bit to reduce the number of messages, but still receive some.
Could it be, that the timeout counter starts when events are read from outlook and not when communication to the remote servers are started?

Thanks for supporting!

Cheers, Lutz.

**Comment by aluxnimm** [comment]
anything in the oc server log as well?

**Comment by big-chen** [comment]
I had a look. No Warnings/Errors during this time period.
    But today, it was quite calm. I restarted the server last
      weekend, now it runs without warnings, timeout set to 300 secs.
    
    I keep an eye on it....
    
    
    Am 05.09.2016 um 13:21 schrieb Alex
      Nimmervoll:
    
    
      anything in the oc server log as well? 
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aluxnimm/outlookcaldavsynchronizer","title":"aluxnimm/outlookcaldavsynchronizer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aluxnimm/outlookcaldavsynchronizer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aluxnimm in #163: anything in the oc server log as well? "}],"action":{"name":"View Issue","url":"https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/163#issuecomment-244723634"}}}

**Comment by aluxnimm** [comment]
ok reopen when issue shows up again.
