### ISSUE TITLE
Error: One or more parameter values are not valid.

### ISSUE THREAD

**Issue by big-chen** [aluxnimm/outlookcaldavsynchronizer#165]
Hi,

I've updated to the latest version 2.5.1.0 and one appointment screws up my Outlook sync:
```
INFO  2016-09-19 08:27:25,309 [ VSTA_Main] ementation.Events.OutlookEventRepository . GetAll                         - Using Outlook DASL filter: @SQL="http://schemas.microsoft.com/mapi/proptag/0x001A001E" = 'IPM.Appointment' And "urn:schemas:calendar:dtstart" < '20.10.2016 00:00' And "urn:schemas:calendar:dtend" > '14.09.2016 00:00'
 INFO  2016-09-19 08:27:28,086 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Starting 'CalDavRepository.GetVersions'
 INFO  2016-09-19 08:27:29,272 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Duration of 'CalDavRepository.GetVersions': 00:00:01.1755460
 INFO  2016-09-19 08:27:29,537 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Starting 'CalDavRepository.Get (4 entitie(s))'
 INFO  2016-09-19 08:27:30,255 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Duration of 'CalDavRepository.Get (4 entitie(s))': 00:00:00.7087695
 INFO  2016-09-19 08:27:30,333 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - Atype delta: Unchanged: 21 , Added: 1 , Deleted 0 ,  Changed 3
 INFO  2016-09-19 08:27:30,333 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - Btype delta: Unchanged: 24 , Added: 1 , Deleted 0 ,  Changed 0
 ERROR 2016-09-19 08:27:31,986 [ VSTA_Main] nSync.Synchronization.States.StateBase`6 . LogException                   - 
System.ArgumentException: Could not complete the operation. One or more parameter values are not valid.
   at Microsoft.Office.Interop.Outlook._AppointmentItem.Save()
   at CalDavSynchronizer.Implementation.ComWrappers.AppointmentItemWrapper.SaveAndReload()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapRecurrance2To1(IEvent source, IReadOnlyCollection`1 exceptions, AppointmentItemWrapper targetWrapper, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IEvent source, IReadOnlyCollection`1 recurrenceExceptionsOrNull, AppointmentItemWrapper targetWrapper, Boolean isRecurrenceException, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, AppointmentItemWrapper target, IEntityMappingLogger logger)
   at GenSync.Synchronization.States.CreateInA`6.<InitializeEntity>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.CreateInA`6.JobWrapper.<InitializeEntity>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.<Create>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__2.MoveNext()
 INFO  2016-09-19 08:27:35,014 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'Arbeit (Lutz)'': 00:00:10.0071126
```
There is no Outlook Id shown, only a Server Id. The remote element looks like this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ddaysoftware.com//NONSGML DDay.iCal 1.0//EN
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYMONTH=10
TZNAME:W. Europe Standard Time
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3
TZNAME:W. Europe Daylight Time
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='B, M';ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;CN="HILKEN, LUTZ";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='B, M';ROLE=OPT-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT;RSV
 P=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
CLASS:PUBLIC
DESCRIPTION:Topic for today: ..............................
 ...................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160330T150000
DTSTAMP:20160909T090641Z
DTSTART;TZID=W. Europe Standard Time:20160330T140000
EXDATE:20160427T120000Z
EXDATE:20160914T120000Z
LOCATION:Skype Meeting
ORGANIZER;CN="B, M";SCHEDULE-AGENT=CLIENT:MAILTO:a@
 ems.com
PRIORITY:5
RRULE:FREQ=WEEKLY;INTERVAL=4;BYDAY=WE
SEQUENCE:6
SUMMARY:[Ops ++] QS
TRANSP:OPAQUE
UID:f3e85b2f-d877-4adf-8a77-ab8884364f2e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='B, M';ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;CN="B, M";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='B, M';ROLE=OPT-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT;RSV
 P=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIPANT
 ;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=OPT-PARTICIP
 ANT;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
CLASS:PUBLIC
DESCRIPTION:Sorry\, I have to postpone it again............................
 ..................................................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160623T120000
DTSTAMP:20160909T090642Z
DTSTART;TZID=W. Europe Standard Time:20160623T110000
LOCATION:Skype Meeting
ORGANIZER;CN="BELY, MIKLOS";SCHEDULE-AGENT=CLIENT:MAILTO:miklos.bely@lhsyst
 ems.com
PRIORITY:5
RECURRENCE-ID:20160622T120000Z
SEQUENCE:7
SUMMARY:[Ops ++] QS
TRANSP:OPAQUE
UID:f3e85b2f-d877-4adf-8a77-ab8884364f2e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;
 RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:jom@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="B, M";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:m@a.de
ATTENDEE;CN="B, M";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:m@a.de
CLASS:PUBLIC
DESCRIPTION:Topic for today: ...........................................
 ..........................................................................
 ...................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160817T150000
DTSTAMP:20160909T090643Z
DTSTART;TZID=W. Europe Standard Time:20160817T140000
LOCATION:Skype Meeting
ORGANIZER;CN="B, M";SCHEDULE-AGENT=CLIENT:MAILTO:m@s
 ems.com
PRIORITY:5
RECURRENCE-ID:20160817T120000Z
SEQUENCE:8
SUMMARY:[Ops ++] QS
TRANSP:OPAQUE
UID:f3e85b2f-d877-4adf-8a77-ab8884364f2e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
END:VCALENDAR
```

Thanks for taking care.

Cheers!

**Comment by aluxnimm** [comment]
can't reproduce. This vevent loads without problem when I test a sync from a SOGo server to Outlook? What server are you using? Did you modify the email adresses I assume? Can you try with "Map organizer and attendees" disabled in event mapping configuration to check if that makes a difference?

**Comment by big-chen** [comment]
I sync from Outlook to ownCloud (Outlook <--> Server, OutlookWins).
Disabling "Map organizer and attendees" helped. Now, enabling it again, it works as well.

... maybe a leftover from a cancelled appointment, the outlook reference was not shown...
And yes, I shortened the emails.

Thanks for helping!
