### ISSUE TITLE
ArgumentException: cannot sync calender entry

### ISSUE THREAD

**Issue by big-chen** [aluxnimm/outlookcaldavsynchronizer#173]
Hi,

with the new version 2.7.0.0 I got this sync error after cleaning the cache (Outlook to ownCloud sync:
```
System.ArgumentException: Could not complete the operation. One or more parameter values are not valid.
   at Microsoft.Office.Interop.Outlook._AppointmentItem.Save()
   at CalDavSynchronizer.Implementation.ComWrappers.AppointmentItemWrapper.SaveAndReload()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapRecurrance2To1(IEvent source, IReadOnlyCollection`1 exceptions, AppointmentItemWrapper targetWrapper, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IEvent source, IReadOnlyCollection`1 recurrenceExceptionsOrNull, AppointmentItemWrapper targetWrapper, Boolean isRecurrenceException, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, AppointmentItemWrapper target, IEntityMappingLogger logger)
   at GenSync.Synchronization.States.CreateInA`6.<InitializeEntity>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.CreateInA`6.JobWrapper.<InitializeEntity>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.<Create>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__2.MoveNext()
```

The remote element looks like this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ddaysoftware.com//NONSGML DDay.iCal 1.0//EN
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYMONTH=10
TZNAME:W. Europe Standard Time
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3
TZNAME:W. Europe Daylight Time
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXY, MXXXS";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="GXXXF, OXXXF";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:OXXXF.GXXXF@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='OXXXF GXXXF';ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:lsygol@outlook.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="VXXXI, MXXXS";ROLE=REQ-PARTICI
 PANT;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.vxxxi@lXXXs
 .com
ATTENDEE;CN="HILKEN, LUTZ";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:lutz.hilken@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="STECHER, DANIEL";ROLE=OPT-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:daniel.stecher@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='Janos Bendes';ROLE=OPT-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:janos.bendes@hu.ibm.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BENDES, JANOS";ROLE=OPT-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="DOMIAN, ANDRAS";ROLE=OPT-PARTICIPANT;RSV
 P=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:andras.domian@lXXXs.com
CLASS:PUBLIC
DESCRIPTION:Topic for today: HYPERLINK "https://xxx.lXXXs.com/is
 sues/?filter=44796"Issues on TBD assigned to QS. We will start with the cu
 stomer issues\n\n.........................................................
 ..........................................................................
 ......\nJoin Skype Meeting\n\nhttps://xxx.de/u203694/8OBJJFVB\n\nThis
  is an online meeting for Skype for Business\, the professional meetings a
 nd communications app formerly known as Lync. \n\nJoin by Phone \n+49 69 6
 96 888 00 (FXXXKfurt Area Location Profile) 		English (United States)  \nF
 ind a local number (https://xxx.de) \n\nConference ID: 649149 \n\n 
 Forgot your dial-in PIN? (https://xxx.de)  |  Help (https://ebase.d
 lh.de/ebase/va/en/CT/bereiche/cti/cti_prod/comBaseUC/combase-uc-support.ht
 ml)       \n\n[!OC([1033])!]\n............................................
 ..........................................................................
 ...................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160323T150000
DTSTAMP:20160930T092155Z
DTSTART;TZID=W. Europe Standard Time:20160323T140000
EXDATE:20160615T120000Z
EXDATE:20161005T120000Z
LOCATION:Skype Meeting
ORGANIZER;CN="BXXXY, MXXXS";SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lhsyst
 ems.com
PRIORITY:5
RRULE:FREQ=WEEKLY;INTERVAL=4;BYDAY=WE
SEQUENCE:19
SUMMARY:[Ops ++] QS
TRANSP:OPAQUE
UID:1bae808d-3024-41ce-bb57-d7c0384ef36e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXY, MXXXS";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="GXXXF, OXXXF";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:OXXXF.GXXXF@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='OXXXF GXXXF';ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:lsygol@outlook.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="VXXXI, MXXXS";ROLE=REQ-PARTICI
 PANT;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.vxxxi@lXXXs
 .com
ATTENDEE;CN="HXXXN, LXXXZ";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:LXXXZ.HXXXN@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="SXXXR, DXXXL";ROLE=OPT-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:DXXXL.SXXXR@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='JXXXS BXXXS';ROLE=OPT-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:JXXXS.BXXXS@hu.ibm.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXS, JXXXS";ROLE=OPT-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="DXXXN, AXXXN";ROLE=OPT-PARTICIPANT;RSV
 P=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:AXXXN.DXXXN@lXXXs.com
CLASS:PUBLIC
DESCRIPTION:Topic for today: HYPERLINK "https://xxx.lXXXs.com/is
 sues/?filter=44796"Issues on TBD assigned to QS. We will start with the cu
 stomer issues\n\n.........................................................
 ..........................................................................
 ......\nJoin Skype Meeting\n\nhttps://xxxx.de/xxxx/8OBJJFVB\n\nThis
  is an online meeting for Skype for Business\, the professional meetings a
 nd communications app formerly known as Lync. \n\nJoin by Phone \n+4xxxx
 00 (FXXXKfurt Area Location Profile) 		English (United States)  \nF
 ind a local number (https://xxx.de) \n\nConference ID: xxx \n\n 
 Forgot your dial-in PIN? (https://xxxx.de)  |  Help (https://xxx.de/
 ebase/va/xxxx.ht
 ml)       \n\n[!OC([1033])!]\n............................................
 ..........................................................................
 ...................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160323T150000
DTSTAMP:20160930T092156Z
DTSTART;TZID=W. Europe Standard Time:20160323T140000
LOCATION:Skype Meeting
ORGANIZER;CN="BXXXY, MXXXS";SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@xxx
 xxx.com
PRIORITY:5
RECURRENCE-ID:20160323T130000Z
SEQUENCE:20
SUMMARY:[XXX ++] QS
TRANSP:OPAQUE
UID:1bae808d-3024-41ce-bb57-d7c0384ef36e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXY, MXXXS";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="GXXXF, OXXXF";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:OXXXF.GXXXF@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="VXXXI, MXXXS";ROLE=REQ-PARTICI
 PANT;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.vxxxi@lXXXs
 .com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='OXXXF GXXXF';ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:lsygol@outlook.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="RAISS, NAIMA";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:naima.raiss@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="SXXXR, DXXXL";ROLE=OPT-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:DXXXL.SXXXR@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="DXXXN, AXXXN";ROLE=OPT-PARTICIPANT;RSV
 P=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:AXXXN.DXXXN@lXXXs.com
ATTENDEE;CN="HXXXN, LXXXZ";PARTSTAT=TENTATIVE;ROLE=OPT-PARTICIPANT;SCHEDULE
 -AGENT=CLIENT:MAILTO:LXXXZ.HXXXN@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='JXXXS BXXXS';ROLE=OPT-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:JXXXS.BXXXS@hu.ibm.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXS, JXXXS";ROLE=OPT-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="WXXXR, FXXXK";ROLE=OPT-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:FXXXK.WXXXR@lXXXs.com
CLASS:PUBLIC
DESCRIPTION:Postponed again as MXXXS is on sick leave.\n\n@Naima: can yo
 u please jump in tomorrow?\n@FXXXK: would you be so kind to represent cust
 omer support?\n\nThanks\nBR\nMiki\n\n\n---\nPostponed due to Mitarbeiterve
 rsammlung am Mittwoch.\n\n--\n\nTopic for today: HYPERLINK "https://xxx
 xxx.lXXXs.com/issues/?filter=44796"Issues on TBD assigned to QS. We w
 ill start with the customer issues\n\n....................................
 ..........................................................................
 ...........................\nJoin Skype Meeting\n\nhttps://xxx.de/u20
 3694/8OBJJFVB\n\nThis is an online meeting for Skype for Business\, the pr
 ofessional meetings and communications app formerly known as Lync. \n\nJoi
 n by Phone \n+49 000 00 (FXXXKfurt Area Location Profile) 		English
  (United States)  \nFind a local number (https://xxx.de) \n\nConfer
 ence ID: 649149 \n\n Forgot your dial-in PIN? (https://xxx.de)  |  
 Help (https://xxx.de/xxx.html)       \n\n[!OC([1033])!]\n.......................
 ..........................................................................
 ........................................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160715T110000
DTSTAMP:20160930T092156Z
DTSTART;TZID=W. Europe Standard Time:20160715T100000
LOCATION:Skype Meeting
ORGANIZER;CN="BXXXY, MXXXS";SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lhsyst
 ems.com
PRIORITY:5
RECURRENCE-ID:20160713T120000Z
SEQUENCE:21
SUMMARY:[Ops ++] QS
TRANSP:TRANSPARENT
UID:1bae808d-3024-41ce-bb57-d7c0384ef36e
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXY, MXXXS";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="VXXXI, MXXXS";ROLE=REQ-PARTICI
 PANT;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.vxxxi@lXXXs
 .com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="WXXXR, FXXXK";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:FXXXK.WXXXR@lXXXs.com
ATTENDEE;CN="HXXXN, LXXXZ";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:LXXXZ.HXXXN@lXXXs.com
CLASS:PUBLIC
DESCRIPTION:We are again on lack of customer supporters.. be prepared for t
 wo QS during the next week \;)\n----\nTopic for today: HYPERLINK "https://
 xxx.lXXXs.com/issues/?filter=44796"Issues on TBD assigned to QS
 . We will start with the customer issues\n\n..............................
 ..........................................................................
 .................................\nJoin Skype Meeting\n\nhttps://xxx.
 de/u203694/8OBJJFVB\n\nThis is an online meeting for Skype for Business\, 
 the professional meetings and communications app formerly known as Lync. \
 n\nJoin by Phone \n+49 000 00 (FXXXKfurt Area Location Profile) 		E
 nglish (United States)  \nFind a local number (https://xxx.de) \n\n
 Conference ID: 649149 \n\n Forgot your dial-in PIN? (https://xxx.de
 )  |  Help (https://xxx.de/xxx.html)       \n\n[!OC([1033])!]\n.................
 ..........................................................................
 ..............................................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160816T113000
DTSTAMP:20160930T092157Z
DTSTART;TZID=W. Europe Standard Time:20160816T103000
LOCATION:Skype Meeting
ORGANIZER;CN="BXXXY, MXXXS";SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@xxx
 xxx.com
PRIORITY:5
RECURRENCE-ID:20160810T120000Z
SEQUENCE:22
SUMMARY:[Ops ++] QS
TRANSP:OPAQUE
UID:1bae808d-3024-41ce-bb57-d7c0384ef36e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="BXXXY, MXXXS";ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="VXXXI, MXXXS";ROLE=REQ-PARTICI
 PANT;RSVP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.vxxxi@lXXXs
 .com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="GXXXF, OXXXF";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:OXXXF.GXXXF@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='OXXXF GXXXF';ROLE=REQ-PARTICIPANT;RSVP=
 TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:lsygol@outlook.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="FREYER, JORGE";ROLE=REQ-PARTICIPANT;RSVP
 =TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:jorge.freyer@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="SXXXR, DXXXL";ROLE=OPT-PARTICIPANT;RS
 VP=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:DXXXL.SXXXR@lXXXs.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN="DXXXN, AXXXN";ROLE=OPT-PARTICIPANT;RSV
 P=TRUE;SCHEDULE-AGENT=CLIENT:MAILTO:AXXXN.DXXXN@lXXXs.com
ATTENDEE;CN="HXXXN, LXXXZ";PARTSTAT=ACCEPTED;ROLE=OPT-PARTICIPANT;SCHEDULE-
 AGENT=CLIENT:MAILTO:LXXXZ.HXXXN@lXXXs.com
CLASS:PUBLIC
DESCRIPTION:Topic for today: HYPERLINK "https://xxx.lXXXs.com/is
 sues/?filter=44796"Issues on TBD assigned to QS. We will start with the cu
 stomer issues\n\n.........................................................
 ..........................................................................
 ......\nJoin Skype Meeting\n\nhttps://xxx.de/u203694/8OBJJFVB\n\nThis
  is an online meeting for Skype for Business\, the professional meetings a
 nd communications app formerly known as Lync. \n\nJoin by Phone \n+49 69 6
 96 888 00 (FXXXKfurt Area Location Profile) 		English (United States)  \nF
 ind a local number (https://xxx.de) \n\nConference ID: 649149 \n\n 
 Forgot your dial-in PIN? (https://xxx.de)  |  Help (https://ebase.d
 lh.de/xxx.ht
 ml)       \n\n[!OC([1033])!]\n............................................
 ..........................................................................
 ...................\n\n\n
DTEND;TZID=W. Europe Standard Time:20160907T150000
DTSTAMP:20160930T092158Z
DTSTART;TZID=W. Europe Standard Time:20160907T140000
LOCATION:Skype Meeting
ORGANIZER;CN="BXXXY, MXXXS";SCHEDULE-AGENT=CLIENT:MAILTO:MXXXS.BXXXY@lhsyst
 ems.com
PRIORITY:5
RECURRENCE-ID:20160907T120000Z
SEQUENCE:23
SUMMARY:[XXX ++] QS
TRANSP:OPAQUE
UID:1bae808d-3024-41ce-bb57-d7c0384ef36e
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
END:VEVENT
END:VCALENDAR
```

Thanks!

Cheers!

**Comment by aluxnimm** [comment]
Can't reproduce. No error when I import this into my server and sync to Outlook. Does it happen during an update of this appointment or a new sync? Maybe try to delete it in Outlook and sync it oneway Outlook <- Server (Replicate)

**Comment by big-chen** [comment]
The error came on update from Outlook --> ownCloud. Also when cleaning 
the cache.
After a new replication Outlook --> ownCloud the sync went well.

**Comment by aluxnimm** [comment]
ok since we don't have an exact scenario for the update we can't reproduce it atm.
