### ISSUE TITLE
NPE after upgrade to 2.8.0

### ISSUE THREAD

**Issue by maybeec** [aluxnimm/outlookcaldavsynchronizer#174]
After upgrading to 2.8.0, I got several NullReferenceExceptions on Calendar sync of the following schema:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IEvent source, IReadOnlyCollection`1 recurrenceExceptionsOrNull, AppointmentItemWrapper targetWrapper, Boolean isRecurrenceException, IEntityMappingLogger logger)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, AppointmentItemWrapper target, IEntityMappingLogger logger)
   at GenSync.Synchronization.States.RestoreInA`6.<UpdateEntity>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.RestoreInA`6.JobWrapper.<UpdateEntity>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.<TryUpdate>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__2.MoveNext()
```

Configuration:

* Windows 7 64bit
* Outlook 2013
* Nextcloud 9.0.53

**Comment by aluxnimm** [comment]
Can you check if it makes any difference when you open and save the sync profile in the options dialog?

**Comment by maybeec** [comment]
Basically, after doing that and waiting some synchronizations, the issues seems to be gone.
However, I am a little bit afraid as I configured a calendar with Replicate Outlook -> Server and got the following three synchronizations:

![capture](https://cloud.githubusercontent.com/assets/1427255/19469120/30ef053e-951a-11e6-8852-dde03d15bc5b.PNG)

![capture](https://cloud.githubusercontent.com/assets/1427255/19469135/3f635f66-951a-11e6-9dc6-37c47852fe26.PNG)

![capture](https://cloud.githubusercontent.com/assets/1427255/19469141/4ad56088-951a-11e6-8afd-45781016e9a8.PNG)

![capture](https://cloud.githubusercontent.com/assets/1427255/19469156/56dd0c50-951a-11e6-82ea-5100e752a637.PNG)

what is happening here?

**Comment by aluxnimm** [comment]
Nullreference Exception when options are not saved fixed in 2.8.1

**Comment by maybeec** [comment]
Thanks. But can you explain, why my outlook data got updated regardless of the sync profile replicate?

**Comment by aluxnimm** [comment]
Nope, nothing got updated in Outlook. This info just shows the detected state before syncing (the delta). So we detected, that 3 items in Outlook have been changed since the last sync and nothing was changed on the server side since last sync.

**Comment by maybeec** [comment]
:+1: thanks. Thus, I miss interpreted the information.
Best support ever!

**Comment by aluxnimm** [comment]
You are welcome :)
