### ISSUE TITLE
Make the "unable to connect to remote server" message less intrusive

### ISSUE THREAD

**Issue by radoeka** [aluxnimm/outlookcaldavsynchronizer#181]
I'm getting the "unable to connect to remote server" message.  This is just after I started my computer, after reviving it from sleep or hibernate mode.  It probably also happens, I regularly switch between VPN and direct network connections.

Is there a possibility, or can it be created and not each missed connection is reported via popup error message.  It would also be good to mentioned / report how often a connection is made and of those connections were successful.  That will make it possible to determine how severe a missed connection actually is.  As long as 1 out of X connections are missed, it does not worry me. 

Is there a possibility to make this part a bit smarter.

```
<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>Owncloud richard</ProfileName>
  <ProfileId>5db44478-05d4-4af5-8b66-f2791f017cc6</ProfileId>
  <StartTime>2016-12-04T06:50:57.1389014Z</StartTime>
  <LoadErrors />
  <EntitySynchronizationReports />
  <ExceptionThatLeadToAbortion>CalDavSynchronizer.DataAccess.WebDavClientException: An error occurred while sending the request. ---&gt; System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 83.x.y.z:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp; context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequest&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReadResponse&gt;d__7.MoveNext()
   --- End of inner exception stack trace ---
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReadResponse&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.&lt;GetVersions&gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.&lt;GetVersions&gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.&lt;GetAllVersions&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.&lt;SynchronizeNoThrow&gt;d__19.MoveNext()</ExceptionThatLeadToAbortion>
  <Duration>00:00:23.8453639</Duration>
</SynchronizationReport>
```

**Comment by aluxnimm** [comment]
Similar to #104.
You are right, we should find a better way to report network issues, but it is hard to distinguish them from real errors and it also depends on the sync interval of course. If you sync every minute and it fails 1 out of 100 times it is less important than if you sync only every hour and it fails once.

But if the url is wrong, the password is not correct (anymore) or the server has some network issues the error shouldn't be ignored.

**Comment by radoeka** [comment]
The sync interval is set at 30 min. 
That's not too often.   I this situation I would like to know how often it goes well.   I also wonder why other programs do not report any network issues (or at least that's what I think.   I've to restart Outlook regularly after waking up the computer).

**Comment by aluxnimm** [comment]
There is a status window accessible from the ribbon where you see if the last sync run was successful and how long ago it happened at least.

**Comment by aluxnimm** [comment]
Finally we tried to improve this behaviour and log the first network errors only as warnings to avoid errors after startup from hibernate for example, will be in 2.19.0.
