### ISSUE TITLE
NPE once occurred

### ISSUE THREAD

**Issue by maybeec** [aluxnimm/outlookcaldavsynchronizer#185]
I once observed an NPE. However, it did not reoccur for a while.
I am posting this not as a bug but maybe it is a look worth if you are interested.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.QueryFolder[T](NameSpace session, GenericComObjectWrapper`1 calendarFolderWrapper, StringBuilder filterBuilder, Func`2 selector)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.GetAll[T](IEnumerable`1 idsOfknownEntities, IEventSynchronizationContext context, Func`2 selector)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.GetAllVersions(IEnumerable`1 idsOfknownEntities, IEventSynchronizationContext context)
   at GenSync.Synchronization.Synchronizer`7.<SynchronizeNoThrow>d__19.MoveNext()
```

**Comment by aluxnimm** [comment]
Thank you, could only happen if the Outlook folder can't be queried and GetTable returns null which shouldn't happen or the folder object itself couldn't be accessed.

**Comment by maybeec** [comment]
Ok, seemingly there is a rare case, where this can happen. So maybe you can silently abort the synchronization with a warning and try it again later? Would be better.

**Comment by aluxnimm** [comment]
Yes, sounds reasonable.
