### ISSUE TITLE
Sync account, access denied

### ISSUE THREAD

**Issue by d3lg** [aluxnimm/outlookcaldavsynchronizer#197]
Hello, I have a configuration error, when trying to configure an account it indicates an access denied error.  I do not know if I need to install any files or additional packages

 INFO  2017-06-05 09:31:36,779 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . ThisAddIn_Startup              - Startup entered.
 INFO  2017-06-05 09:31:37,748 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . ThisAddIn_Startup              - Startup exiting.
 INFO  2017-06-05 09:31:55,110 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - StartupTimer_Tick entered.
 INFO  2017-06-05 09:32:00,000 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Startup...
 INFO  2017-06-05 09:32:32,844 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - Initializing component container.
 INFO  2017-06-05 09:32:33,706 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - StartupTimer_Tick exiting.
 ERROR 2017-06-05 09:33:30,855 [ VSTA_Main] ViewModels.GoogleServerSettingsViewModel . MoveNext                       - Exception while testing the connection.
System.Net.HttpListenerException (0x80004005): Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.StartListener()
   at Google.Apis.Auth.OAuth2.LocalServerCodeReceiver.<ReceiveCodeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Apis.Auth.OAuth2.AuthorizationCodeInstalledApp.<AuthorizeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.OAuth.Google.GoogleHttpClientFactory.<LoginToGoogle>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.OAuth.Google.GoogleHttpClientFactory.<CreateHttpClient>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CalDavSynchronizer.Scheduling.SynchronizerFactory.<CreateHttpClient>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.WebDavDataAccess.<GetCurrentUserPrincipalUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetUserResourcesNoThrow>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Ui.Options.OptionTasks.<DoAutoDiscovery>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CalDavSynchronizer.Ui.Options.OptionTasks.<TestGoogleConnection>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Ui.Options.ViewModels.GoogleServerSettingsViewModel.<TestConnectionAsync>d__21.MoveNext()

**Comment by aluxnimm** [comment]
Fixed in 2.22.0.
