### ISSUE TITLE
Can't get Timezone of AppointmentItem, using UTC

### ISSUE THREAD

**Issue by mfe-** [aluxnimm/outlookcaldavsynchronizer#219]
Hi,

after installing and starting synching I get the following error:

Is there a way to determine the problem item in outlook, so I can delete it?

`<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ProfileName>all calendar</ProfileName>
  <ProfileId>e07765a8-ab44-4b17-b8f9-2fd6418650a8</ProfileId>
  <StartTime>2017-12-06T13:33:20.4924341Z</StartTime>
  <ADelta>Unchanged: 87 , Added: 1 , Deleted 0 ,  Changed 0</ADelta>
  <BDelta>Unchanged: 87 , Added: 0 , Deleted 0 ,  Changed 0</BDelta>
  <AJobsInfo>Create 0 , Update 0 , Delete 0</AJobsInfo>
  <BJobsInfo>Create 1 , Update 0 , Delete 0</BJobsInfo>
  <LoadErrors />
  <EntitySynchronizationReports>
    <EntitySynchronizationReport>
      <MappingErrors />
      <MappingWarnings>
        <string>Can't get Timezone of AppointmentItem, using UTC</string>
      </MappingWarnings>
      <AId>0000000095763AC1B876654388C1D5C74F6B382207005C791D95ADB4364CB5C5086A18C410E400000000010D00005C791D95ADB4364CB5C5086A18C410E40000F17C755E0000</AId>
      <ExceptionThatLeadToAbortion>System.Runtime.InteropServices.COMException (0x9EE70057): Sorry, something went wrong. You may want to try again.
   at Microsoft.Office.Interop.Outlook._AppointmentItem.get_AllDayEvent()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItem source, IEvent target, Boolean isRecurrenceException, ITimeZone startIcalTimeZone, ITimeZone endIcalTimeZone, IEntityMappingLogger logger, IEventSynchronizationContext context)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.&lt;Map1To2&gt;d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.CreateInB`7.&lt;InitializeEntity&gt;d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.CreateInB`7.JobWrapper.&lt;InitializeEntity&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.&lt;Create&gt;d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.&lt;PerformOperations&gt;d__3.MoveNext()</ExceptionThatLeadToAbortion>
      <Operation>CreateInB</Operation>
    </EntitySynchronizationReport>
  </EntitySynchronizationReports>
  <ConsiderExceptionThatLeadToAbortionAsWarning>false</ConsiderExceptionThatLeadToAbortionAsWarning>
  <Duration>00:00:01.4846530</Duration>
</SynchronizationReport>`

**Comment by nertsch** [comment]
Probably start or enddate is missing.
br
Gerhard

**Comment by aluxnimm** [comment]
And since it is an allday even sort by that in list view
