### ISSUE TITLE
SystemArgumentException syncing with Nextcloud 13.

### ISSUE THREAD

**Issue by truschival** [aluxnimm/outlookcaldavsynchronizer#223]
Since the server upgrade to Nextcloud 13.0 the synchronization fails. 
I am using version outlook 365 Pro Version1708 and outlookcaldavsynchronizer version  3.0.0

The error reported is:
```
<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>Owncloud_Sync</ProfileName>
  <ProfileId>5a43b3e0-501e-4a16-b515-28fb4da8afc6</ProfileId>
  <StartTime>2018-03-13T06:57:24.9149733Z</StartTime>
  <ADelta>Unchanged: 13 , Added: 0 , Deleted 0 ,  Changed 5</ADelta>
  <BDelta>Unchanged: 18 , Added: 2 , Deleted 0 ,  Changed 0</BDelta>
  <AJobsInfo>Create 0 , Update 5 , Delete 0</AJobsInfo>
  <BJobsInfo>Create 0 , Update 0 , Delete 0</BJobsInfo>
  <LoadErrors>
    <LoadError>
      <EntityId>/remote.php/dav/calendars/ruschi/defaultcalendar/1520884978.R184.ics</EntityId>
      <Error>System.ArgumentException: Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive.
   at DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.CheckMutuallyExclusive[T,U](String name1, String name2, T obj1, U obj2)
   at DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.Deserialize(TextReader tr)
   at DDay.iCal.Serialization.iCalendar.DataMapSerializer.Deserialize(TextReader tr)
   at DDay.iCal.iCalParser.property(ISerializationContext ctx, ICalendarPropertyListContainer c)
   at DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   at DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   at DDay.iCal.iCalParser.icalbody(ISerializationContext ctx, IICalendar iCal)
   at DDay.iCal.iCalParser.icalendar(ISerializationContext ctx)
   at DDay.iCal.Serialization.iCalendar.iCalendarSerializer.Deserialize(TextReader tr)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.DeserializeCalendar(String iCalData, IStringSerializer calendarSerializer)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.TryDeserializeCalendar(String iCalData, IICalendar&amp; calendar, WebResourceName uriOfCalendarForLogging, IStringSerializer calendarSerializer, ILoadEntityLogger logger)</Error>
      <IsAEntity>false</IsAEntity>
      <IsWarning>false</IsWarning>
    </LoadError>
    <LoadError>
      <EntityId>/remote.php/dav/calendars/ruschi/defaultcalendar/1520884988.R777.ics</EntityId>
      <Error>System.ArgumentException: Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive.
   at DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.CheckMutuallyExclusive[T,U](String name1, String name2, T obj1, U obj2)
   at DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.Deserialize(TextReader tr)
   at DDay.iCal.Serialization.iCalendar.DataMapSerializer.Deserialize(TextReader tr)
   at DDay.iCal.iCalParser.property(ISerializationContext ctx, ICalendarPropertyListContainer c)
   at DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   at DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   at DDay.iCal.iCalParser.icalbody(ISerializationContext ctx, IICalendar iCal)
   at DDay.iCal.iCalParser.icalendar(ISerializationContext ctx)
   at DDay.iCal.Serialization.iCalendar.iCalendarSerializer.Deserialize(TextReader tr)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.DeserializeCalendar(String iCalData, IStringSerializer calendarSerializer)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.TryDeserializeCalendar(String iCalData, IICalendar&amp; calendar, WebResourceName uriOfCalendarForLogging, IStringSerializer calendarSerializer, ILoadEntityLogger logger)</Error>
      <IsAEntity>false</IsAEntity>
      <IsWarning>false</IsWarning>
    </LoadError>
  </LoadErrors>
  <EntitySynchronizationReports />
  <ConsiderExceptionThatLeadToAbortionAsWarning>false</ConsiderExceptionThatLeadToAbortionAsWarning>
  <Duration>00:00:03.7434754</Duration>
</SynchronizationReport>

```

**Comment by nertsch** [comment]
The Server returns an Event with an invalid recurrence Pattern.
Probably the best approach is to delete it (or just the recurrence pattern) an create it new
br
Gerhard

**Comment by truschival** [comment]
Thanks for the help - deleting the event fixed it!
