### ISSUE TITLE
"System.UnauthorizedAccessException" when updating VEVENT object

### ISSUE THREAD

**Issue by vgallotsimplexe** [aluxnimm/outlookcaldavsynchronizer#229]
We are using outlookcaldavsynchronizer with a sabredav server.
One of our users got à problem when updating when running a sync.

```
<ExceptionThatLeadToAbortion>System.UnauthorizedAccessException: Vous n'avez pas les autorisations suffisantes pour effectuer cette opération sur cet objet. Veuillez vous mettre en rapport avec le contact de ce dossier ou votre administrateur système.
at Microsoft.Office.Interop.Outlook.AddressEntry.GetContact()
at CalDavSynchronizer.Implementation.Common.OutlookUtility.GetEmailAdressOrNull(AddressEntry addressEntry, IEntityMappingLogger logger, ILog generalLogger)
at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapAttendees1To2(AppointmentItem source, IEvent target, Boolean&amp; organizerSet, IEntityMappingLogger logger)
at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItem source, IEvent target, Boolean isRecurrenceException, ITimeZone startIcalTimeZone, ITimeZone endIcalTimeZone, IEntityMappingLogger logger, IEventSynchronizationContext context)
at CalDavSynchronizer.Implementation.Events.EventEntityMapper.&lt;Map1To2&gt;d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at GenSync.Synchronization.States.UpdateAToB`7.&lt;UpdateEntity&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at GenSync.Synchronization.States.UpdateAToB`7.JobWrapper.&lt;UpdateEntity&gt;d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CalDavSynchronizer.Implementation.CalDavRepository`1.&lt;TryUpdate&gt;d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.&lt;PerformOperations&gt;d__3.MoveNext()</ExceptionThatLeadToAbortion>
<Operation>UpdateInB</Operation>
```

the event seems to be ok on sabredav server.
what does that mean?

some of events don't have any issues reports.

thanks 
regards

**Comment by aluxnimm** [comment]
Just means that one attendee cant be accessed in Outlook. Do you use an exchange account andhave insufficient rights to access some contact folder or GAL?

We can catch the error and only log a warning in next release.

**Comment by vgallotsimplexe** [comment]
thanks for answer
exactly, there is an exchange server

So, we'll wait for next release! :-)
is there any planned date?

thanks
regards

**Comment by aluxnimm** [comment]
You should investige why the user has no access to the contact folder and ask your exchange admin.
Next release will be scheduled in next days.
