### ISSUE TITLE
Could not load file or assembly NodaTime

### ISSUE THREAD

**Issue by fluboi** [aluxnimm/outlookcaldavsynchronizer#231]
Hi,
I've updated to v3.1.1.0 this morning, and now I do have the following error on one of my calendar:

```
System.IO.FileLoadException: Could not load file or assembly 'NodaTime, Version=2.2.4.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NodaTime, Version=2.2.4.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1'
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map1To2(AppointmentItem source, IEvent target, Boolean isRecurrenceException, ITimeZone startIcalTimeZone, ITimeZone endIcalTimeZone, IEntityMappingLogger logger, IEventSynchronizationContext context)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.<Map1To2>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.UpdateAToB`7.<UpdateEntity>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.UpdateAToB`7.JobWrapper.<UpdateEntity>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<TryUpdate>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__3.MoveNext()
```
Windows 10
Outlook version 1708 

Let me know if you need others infos/logs.

**Comment by sfranken-smartwireless** [comment]
I have the same issue here.

**Comment by aluxnimm** [comment]
Did you try uninstall and install a fresh 3.2.0

**Comment by fluboi** [comment]
In fact the update I receive this morning was the 3.2.0. But it seems the restarting Outlook is mandatory to have the caldavsynchronizer load the new version. 
By simply restating Outlook, the error disappear. 
@sfranken-smartwireless does restarting your outlook also solve the problem for you ?

**Comment by aluxnimm** [comment]
Well thats nothing new and the update even shows a message box that a restart is required

**Comment by SreeniC** [comment]
I have the same issue for MS Build, Build failed due to this.
Any solutions.. ?
