### ISSUE TITLE
System.Security.Cryptography.CryptographicException: SignatureDescription could not be created for the signature algorithm supplied.

### ISSUE THREAD

**Issue by bunyevacz** [aluxnimm/outlookcaldavsynchronizer#233]
First I installed the application successfully. And also synchronized calendar events successfully.
After quiting outlook 2013, and restarting it, I have the following error:

```
Name: 
From: file:///C:/Program Files (x86)/CalDavSynchronizer/CalDavSynchronizer.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: Exception reading manifest from 
file:///C:/Program%20Files%20(x86)/CalDavSynchronizer/CalDavSynchronizer.vsto source. 
the manifest may not be valid or the file could not be opened. ---> System.Deployment.Application.InvalidDeploymentException: Manifest XML signature is not valid.
 ---> System.Security.Cryptography.CryptographicException: SignatureDescription could not be created for the signature algorithm supplied.
   at: System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at: System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
   at: System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
   at: System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
      --- End of inner exception stack trace ---
   at: System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   at: System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
      --- End of inner exception stack trace ---
   at: Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at: Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
```

My system information:
Windows 8.1 Pro, 64bit, 8GB ram, 
Microsoft Office 2013 (and outlook 2013)

Office tools 2010, and .NET 4.6.2 installed.

What I tried so far:
- I removed, and reinstalled OutlookCaldavsynchronizer many times, I tried rebooting inbetween.
- I removed, rebooted, launched `rundll32 dfshim CleanOnlineAppCache` [command](https://stackoverflow.com/questions/2418542/clear-the-net-downloaded-application-cache-without-mage) in commandline (both as normal user, and as elevated commandline), rebooted, reinstalled Outlook Caldavsynchronizer 3.2.0 (latest), rebooted, launched outlook 2013
- I have the latest windows updates (KB4099635) installed on 2018.06.28.
- I reinstalled Visual Studio 2010 Tools for Office Runtime (md5sums): 
```
72F6A267DE1FA813073DED67D952FD40  vstor_redist(1).exe
3472E52F9641FC4BCC471B8CBF897223  vstor_redist(2).exe
A4B529647945755CA27C3560CFB96D86  vstor_redist.exe

    - https://www.microsoft.com/en-us/download/confirmation.aspx?id=54251
    - https://www.microsoft.com/en-us/download/confirmation.aspx?id=48217
    - https://www.microsoft.com/net/download/thank-you/net452
```

- I have read issue [63](https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/63) (for ms office tool reinstalling), the related [sourceforge issue 583](https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/583/).
- I have installed version 3.2.0, 3.1.1, 3.1.0, 3.0.0, 2.27.0 from the [release](https://github.com/aluxnimm/outlookcaldavsynchronizer/releases) page. The same error with all of the versions.
- I have installed the unsupported .NET 4.7 version from [microsoft](https://download.microsoft.com/download/D/D/3/DD35CC25-6E9C-484B-A746-C5BE0C923290/NDP47-KB3186497-x86-x64-AllOS-ENU.exe), because it is maybe a .NET 4.6.2 [bug](https://github.com/Microsoft/dotnet/issues/430). Still the exact same error.
The file I installed (md5sum): 
```
.\NDP47-KB3186497-x86-x64-AllOS-ENU.exe B59040E489BFF55433508438627D11E6
```

My .NET version right now (`regedit`):
` HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full`, Release: `460805`, which is [according](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#net_b) to this page, is .NET 4.7.0

The problem still persist. The exact same error message, no matter what I try.

I tried to see the log file (`C:\Users\user.DOMAIN\AppData\Local\CalDavSynchronizer\log`), 
but there are no error regarding this issue. There are some error when it was running, for ex:
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapAttendeesAndOrganizer2To1(IEvent source, AppointmentItem target, IEntityMappingLogger logger)
 WARN  2018-06-28 12:03:16,151 [ VSTA_Main] .Implementation.Events.EventEntityMapper . MapAttendeesAndOrganizer2To1   - Ignoring invalid Uri in organizer email.
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapAttendeesAndOrganizer2To1(IEvent source, AppointmentItem target, IEntityMappingLogger logger)
 WARN  2018-06-28 12:03:16,152 [ VSTA_Main] .Implementation.Events.EventEntityMapper . MapReminder2To1                - Event '0d74eb46-b71d-4843-a590-17e747525490' contains multiple alarms. Ignoring all except first.
 INFO  2018-06-28 12:03:16,161 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - A repository jobs: Create 77 , Update 0 , Delete 0
 INFO  2018-06-28 12:03:16,161 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - B repository jobs: Create 0 , Update 0 , Delete 0
 INFO  2018-06-28 12:03:16,183 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'istvan_naptar'': 00:01:02.2666416
 INFO  2018-06-28 12:03:26,480 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Partial sync: Running synchronization profile 'istvan_naptar''
 INFO  2018-06-28 12:03:26,497 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Entered partial. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`7' with Atype='IAppointmentItemWrapper' and Btype='IICalendar'
 INFO  2018-06-28 12:03:26,518 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Exiting partial since there is nothing to synchronize.
 INFO  2018-06-28 12:03:26,526 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Partial sync: Running synchronization profile 'istvan_naptar'': 00:00:00.0440559
 INFO  2018-06-28 12:09:16,686 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2018-06-28 12:09:16,804 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'istvan_naptar''
 INFO  2018-06-28 12:09:16,805 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`7' with Atype='IAppointmentItemWrapper' and Btype='IICalendar'
 INFO  2018-06-28 12:09:17,029 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Starting 'CalDavRepository.GetVersions'
 INFO  2018-06-28 12:09:30,726 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Duration of 'CalDavRepository.GetVersions': 00:00:13.6954683
 INFO  2018-06-28 12:09:30,732 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Atype delta: Unchanged: 77 , Added: 0 , Deleted 0 ,  Changed 0
 INFO  2018-06-28 12:09:30,733 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Btype delta: Unchanged: 77 , Added: 0 , Deleted 0 ,  Changed 0
 INFO  2018-06-28 12:09:30,734 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - A repository jobs: Create 0 , Update 0 , Delete 0
 INFO  2018-06-28 12:09:30,735 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - B repository jobs: Create 0 , Update 0 , Delete 0
 INFO  2018-06-28 12:09:30,737 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'istvan_naptar'': 00:00:13.9323211
 INFO  2018-06-28 12:10:15,957 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . ThisAddIn_Startup              - Startup entered.
 INFO  2018-06-28 12:10:15,995 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . ThisAddIn_Startup              - Startup exiting.
 INFO  2018-06-28 12:10:17,989 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - StartupTimer_Tick entered.
 INFO  2018-06-28 12:10:18,112 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Startup...
 INFO  2018-06-28 12:10:18,113 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Version: 3.2.0.0
 INFO  2018-06-28 12:10:18,114 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . .ctor                          - Operating system: Microsoft Windows NT 6.2.9200.0
 INFO  2018-06-28 12:10:19,108 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - Initializing component container.
 INFO  2018-06-28 12:10:19,755 [ VSTA_Main]             CalDavSynchronizer.ThisAddIn . MoveNext                       - StartupTimer_Tick exiting.
 INFO  2018-06-28 12:11:15,734 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2018-06-28 12:11:15,876 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'istvan_naptar''
 INFO  2018-06-28 12:11:15,888 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`7' with Atype='IAppointmentItemWrapper' and Btype='IICalendar'
 INFO  2018-06-28 12:11:16,297 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Starting 'CalDavRepository.GetVersions'
 INFO  2018-06-28 12:11:21,477 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Duration of 'CalDavRepository.GetVersions': 00:00:05.1777498
 INFO  2018-06-28 12:11:21,517 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Atype delta: Unchanged: 77 , Added: 1 , Deleted 0 ,  Changed 0
 INFO  2018-06-28 12:11:21,518 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - Btype delta: Unchanged: 77 , Added: 0 , Deleted 0 ,  Changed 0
 INFO  2018-06-28 12:11:21,904 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - A repository jobs: Create 0 , Update 0 , Delete 0
 INFO  2018-06-28 12:11:21,905 [ VSTA_Main]  GenSync.Synchronization.Synchronizer`11 . MoveNext                       - B repository jobs: Create 1 , Update 0 , Delete 0
```

But it was working. I still have all the previously synchronized events in outlook calendar, just I miss the Caldav synchronizer menu item.

I'm really out of ideas. Any help is much appreciated.

**Comment by bunyevacz** [comment]
As an update, I created a brand new user on windows 8.1, but still the exact same error message.

**Comment by aluxnimm** [comment]
see https://sourceforge.net/p/outlookcaldavsynchronizer/discussion/general/thread/794793bf71/
