### ISSUE TITLE
System.Runtime.InteropServices.COMException (0x80004005)

### ISSUE THREAD

**Issue by talvdav** [aluxnimm/outlookcaldavsynchronizer#284]
Hi, 
when i try to sync my Nextcloud Calendar (self hostet) the sync works fine the first time for the Calendar but every other sync it errors out with this error:
 
```
System.Runtime.InteropServices.COMException (0x80004005): Schlüsselwörter für den Inhaltsindex können für die Einschränkung nicht verwendet werden. Die Sofortsuche ist für diesen Speicher nicht aktiviert.
   at Microsoft.Office.Interop.Outlook.MAPIFolder.GetTable(Object Filter, Object TableContents)
   at CalDavSynchronizer.Implementation.Common.QueryOutlookFolderByGetTableStrategy.CalDavSynchronizer.Implementation.Common.IQueryOutlookAppointmentItemFolderStrategy.QueryAppointmentFolder(IOutlookSession session, Folder calendarFolder, String filter, IGetVersionsLogger logger)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.GetAll(IEnumerable`1 idsOfknownEntities, IEventSynchronizationContext context, IGetVersionsLogger logger)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.<GetAllVersions>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.EntityRepositories.VersionAwareToStateAwareEntityRepositoryAdapter`4.<GetFullRepositoryState>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.Synchronizer`11.<Synchronize>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.ContextCreatingSynchronizerDecorator`7.<Synchronize>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Scheduling.SynchronizationProfileRunner.<RunAndRescheduleNoThrow>d__22.MoveNext()
```

Contacts error out always with the same error.

Microsoft Office Home and Business 2019
outlookcaldavsynchronizer version 3.8.2
Nextcloud version 19.0.3

**Comment by aluxnimm** [comment]
Can you try with general option "Use fast queries for Outlook folders" disabled?
What Outlook profile type are you using? imap account, exchange or local data pst file? You have some issue with the data storage and search indexing.
