### ISSUE TITLE
Contacts sync with Google, error 400

### ISSUE THREAD

**Issue by filippobottega** [aluxnimm/outlookcaldavsynchronizer#324]
Syncing Outlook contacts with Google contacts I get this exception:

```
Google.GData.Client.GDataRequestException: Execution of request failed: https://www.google.com/m8/feeds/groups/xxxxxxxxxxxxxxxx/full?start-index=26&max-results=25 ---> System.Net.WebException: Errore del server remoto: (400) Richiesta non valida.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GOAuth2Request.Execute()
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Client.Feed`1.get_AtomFeed()
   at Google.GData.Client.Feed`1.<get_Entries>d__0.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at CalDavSynchronizer.Implementation.GoogleContacts.GoogleGroupCache.Fill() in C:\outlookcaldavsynchronizer\CalDavSynchronizer\Implementation\GoogleContacts\GoogleGroupCache.cs:line 43
   at CalDavSynchronizer.Implementation.GoogleContacts.GoogleContactContextFactory.<Create>b__5_0() in C:\outlookcaldavsynchronizer\CalDavSynchronizer\Implementation\GoogleContacts\GoogleContactContextFactory.cs:line 55
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CalDavSynchronizer.Implementation.GoogleContacts.GoogleContactContextFactory.<Create>d__5.MoveNext() in C:\outlookcaldavsynchronizer\CalDavSynchronizer\Implementation\GoogleContacts\GoogleContactContextFactory.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GenSync.Synchronization.Synchronizer`11.<SynchronizePartial>d__28.MoveNext() in C:\outlookcaldavsynchronizer\GenSync\Synchronization\Synchronizer.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GenSync.Synchronization.ContextCreatingSynchronizerDecorator`7.<SynchronizePartial>d__4.MoveNext() in C:\outlookcaldavsynchronizer\GenSync\Synchronization\ContextCreatingSynchronizerDecorator.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CalDavSynchronizer.Synchronization.OutlookSynchronizer`2.<SynchronizePartial>d__3.MoveNext() in C:\outlookcaldavsynchronizer\CalDavSynchronizer\Synchronization\OutlookSynchronizer.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CalDavSynchronizer.Scheduling.SynchronizationProfileRunner.<RunPartialNoThrow>d__23.MoveNext() in C:\outlookcaldavsynchronizer\CalDavSynchronizer\Scheduling\SynchronizationProfileRunner.cs:line 297
```

If I retry sometimes the exception is raised and sometimes the synchronisation process ends without errors.

**Comment by EddyXorb** [comment]
I have the same issue.

**Comment by felipelrz** [comment]
Please check [this thread](https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/333#issuecomment-991658861) for a possible solution.
