### ISSUE TITLE
IO problems after latest release.

### ISSUE THREAD

**Issue by Lars-EWE** [aluxnimm/outlookcaldavsynchronizer#385]
After the latest release i get this error when trying to synchronize my existing calendars with new events:
```
System.IO.FileLoadException: Could not load file or assembly 'NodaTime, Version=3.1.0.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NodaTime, Version=3.1.0.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1'
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.MapRecurrance2To1(IEvent source, IReadOnlyCollection`1 exceptions, IAppointmentItemWrapper targetWrapper, IEntitySynchronizationLogger logger, IEventSynchronizationContext context)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IEvent source, IReadOnlyCollection`1 recurrenceExceptionsOrNull, IAppointmentItemWrapper targetWrapper, Boolean isRecurrenceException, IEntitySynchronizationLogger logger, IEventSynchronizationContext context)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, IAppointmentItemWrapper target, IEntitySynchronizationLogger logger, IEventSynchronizationContext context)
   at GenSync.Synchronization.States.CreateInA`7.<InitializeEntity>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.CreateInA`7.JobWrapper.<InitializeEntity>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.<Create>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__3.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
And in the screenshot below is an error I get when i try to make create a new calendar folder for a new calendar profile.
![2023-03-23_09-28](https://user-images.githubusercontent.com/124696552/227147957-8d8287fb-326f-4cee-ac59-a702728ea2ff.png)

**Comment by aluxnimm** [comment]
You need to restart Outlook after every update.

**Comment by Lars-EWE** [comment]
That fixed it, thanks for the support. There should probably be more descriptive error messages, if the restart isn't enforced, and the error happens after every update.
