### ISSUE TITLE
Sync exception since Version 4.4.1

### ISSUE THREAD

**Issue by dylancollaud** [aluxnimm/outlookcaldavsynchronizer#394]
Hi, 
Since last version we got some exceptions (All same) linked apparently to privat event in calendar

> System.NullReferenceException: Object reference not set to an instance of an object.
   at DDay.iCal.Event.get_IsAllDay()
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IEvent source, IReadOnlyCollection`1 recurrenceExceptionsOrNull, IAppointmentItemWrapper targetWrapper, Boolean isRecurrenceException, IEntitySynchronizationLogger logger, IEventSynchronizationContext context)
   at CalDavSynchronizer.Implementation.Events.EventEntityMapper.Map2To1(IICalendar sourceCalendar, IAppointmentItemWrapper target, IEntitySynchronizationLogger logger, IEventSynchronizationContext context)
   at GenSync.Synchronization.States.UpdateBToA`7.<UpdateEntity>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.States.UpdateBToA`7.JobWrapper.<UpdateEntity>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Events.OutlookEventRepository.<TryUpdate>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__3.MoveNext()

We sync with Infomaniak system in Switzerland. Maybe the error come from them.

The exception seems to be "NullReferenceException". 

Thank you for your help.

**Comment by aluxnimm** [comment]
Can you post the ics file of the event in the sync report that causes this error?

**Comment by dylancollaud** [comment]
I don't know if this is this file you need : 

[34adb592-268f-48c8-9924-800d4af57ddf20230502172342010.log](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/11376025/34adb592-268f-48c8-9924-800d4af57ddf20230502172342010.log)

This file was in AppData/Local/CalDavSynchronizer/xxx

**Comment by aluxnimm** [comment]
In this sync report there should be a link to server id and there you can download the raw data of that event, /calendars/JC05088/bff3257e-239f-47cb-bbc1-1cb1ca40bccd/8b6cf2dd-f159-477c-994e-811ddfeeff53.ics

**Comment by dylancollaud** [comment]
Here you can find the file : 

[8b6cf2dd-f159-477c-994e-811ddfeeff53.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/11380950/8b6cf2dd-f159-477c-994e-811ddfeeff53.txt)


I change the extension to .txt but this is my .ics. (Github don't accept this extension)
